#Site configuration
title: Guilherme Esgario
author: Guilherme Esgario
work:  Engenheiro de Computação
year: 2019

url: http://guilhermeesgario.com.br

#Build settings
markdown: kramdown
permalink: /:categories/:title

# Section 2
sec1: "Things I Can Do"
sec5: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer lorem ipsum dolor sit amet."
icon1: "fas fa-code"
icont1: "Write all the code"
icon2: "fa-cubes"
icont2: "Stack small boxes"
icon3: "fa-book"
icont3: "Read books and stuff"
icon4: "fa-coffee"
icont4: "Drink much coffee"
icon5: "fa-bolt"
icont5: "Lightning bolt"
icon6: "fa-users"
icont6: "Shadow clone technique"

# Social Links
#facebook: username
#twitter:  username
#google: username
instagram: guilhermeesgario
#pinterest: username
linkedin: guilhermeesgario
#youtube: username
github: esgario
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: guilherme.esgario@gmail.com