#Site configuration
title: Guilherme Esgario
author: Guilherme Esgario
work:  Engenheiro de Computação
year: 2019

url: http://guilhermeesgario.com.br

#Build settings
markdown: kramdown
permalink: /:categories/:title

# Social Links
#facebook: username
#twitter:  username
#google: username
instagram: guilhermeesgario
#pinterest: username
linkedin: guilhermeesgario
#youtube: username
github: esgario
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: guilherme.esgario@gmail.com